title: "[Bug] : "
labels: ["Beta_test_bug_report"]

body:
  - type: markdown
    attributes:
      value: |
        ## 테스트 App 주의 사항!
        - 가사가 없는 것이 있을 수 있습니다.
        - 건의사항 페이지 버그 제보는 이용하시면 안됩니다 (기능은 사용할 수 있지만 트래픽 당 서버 요금이 청구되어 베타테스트 때는 사용하지 않을 겁니다)
  - type: input
    id: contact
    attributes:
      label: 연락처
      description: "디스코드 아이디를 입력해 주세요."
      placeholder: ex) Hees#0092
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android 버전
      description: "사용하고 계신 기기의 Android 버전을 입력해 주세요."
      placeholder: ex) 13
    validations:
      required: true
  - type: input
    id: phone-num
    attributes:
      label: 휴대폰 기종
      description: "사용하고 계신 휴대폰 기종을 입력해 주세요."
      placeholder: ex) Galaxy S21 Ultra
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 로그인 플랫폼
      description: "로그인한 방식을 선택해 주세요."
      options:
        - 로그인 안함
        - Google
        - Naver
    validations:
      required: true
  - type: textarea
    attributes:
      label: 버그 상세설명
      description: |
        버그를 상세히 설명해 주세요!
      placeholder: |
        ex) 이전에 어떤 행동을 한 후 해당 액션을 취하니 이런 버그가 뜸
    validations:
      required: true
  - type: textarea
    attributes:
      label: 첨부파일
      description: |
        사진을 올리고 싶을 경우 사진을 드래그 앤 드랍 해주시면 됩니다. 만약 영상을 올리고 싶을 경우, 디스코드 버그 제보 채널에  영상을 올리고 그 영상의 링크를 내용에 첨부해주시면 됩니다.
      placeholder: |
        ex) 사진 혹은 [http:.....]\
    validations:
      required: true
