## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.waktaverse.music.** { *; }
-keep class com.waktaverse.music.audio_service.** { *; }
-keep class kotlinx.coroutines.android.** { *; }
-keep class kotlinx.coroutines.core.** { *; }
-dontwarn io.flutter.embedding.**